apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-shell-pod
  namespace: cloudsec-labops-vulnerable
  labels:
    app: vulnerable-shell
spec:
  containers:
    - name: vulnerable-shell
      image: alpine:3.19
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Vulnerable pod started";
          sleep 3600
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory
