name: Secrets Detection

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lightweight-secret-detector:
    name: Run Lightweight Secret Detector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom secret detector on secure folders
        run: python3 scripts/secrets-detect.py secrets/lab08-secrets-detection/secure

  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks on secure folders
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: secrets/lab08-secrets-detection/gitleaks/gitleaks.toml
          args: detect --source secrets/lab08-secrets-detection/secure --no-git --redact --verbose
